export default {
    INCREMENT: 'INCREMENT',
    DECREMENT:"DECREMENT",
    LOGIN:"LOGIN",
    SIGNUP:"SIGNUP",
    CLEAR_REDUX_STATE: 'CLEAR_REDUX_STATE',
    NO_INTERNET: 'NO_INTERNET',
    LANGUAGE_UPDATE : 'LANGUAGE_UPDATE',
    LANGUAGE_ERROR : 'LANGUAGE_ERROR',
    CAMPAIGN_DATA:"CAMPAIGN_DATA",
    CAMPAIGN_ERROR:"CAMPAIGN_ERROR",
    CAMPAIGN_LOADING:"CAMPAIGN_LOADER",
    USER_DATA:"USER_DATA"
}